[package]
authors = ["albx79 <otrebla79>"]
edition = "2018"
name = "what-bump"
version = "0.0.0-SET-ME"
license = "BSD-3-Clause"
description = "Detect required version bump based on conventional commit messages"

[dependencies]
semver = "0.9"
structopt = "0.3.3"
simple-error = "0.2"
fallible-iterator = "0.2.0"
askama = "0.8"
chrono = "0.4.9"

[dependencies.git2]
version = "0.10"
default-features = false
