[package]
authors = ["albx79 <otrebla79>"]
edition = "2018"
name = "what-bump"
version = "0.1.0"

[dependencies]
semver = "0.9"
structopt = "0.3.2"

[dependencies.git2]
version = "0.10"
default-features = false
