version: 2.1

jobs:
  build:
    docker:
      - image: ekidd/rust-musl-builder:1.57.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Skip post-release commit
          command: |
            shopt -s nocasematch
            case $(git log --oneline --format=%B -n 1 HEAD) in "chore: restore UNRELEASED version") circleci step halt;; esac
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - &cacheKey v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build what-bump
          command: cargo build --release
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/x86_64-unknown-linux-musl/.fingerprint
            - target/x86_64-unknown-linux-musl/build
            - target/x86_64-unknown-linux-musl/deps
          key: *cacheKey
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/what-bump

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - skyita-mobile
