version: 2

jobs:
  build:
    docker:
      - image: ekidd/rust-musl-builder:1.38.0
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/what-bump
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Publish Release on GitHub
          command: |
            pwd
            ls -l
            ls -l ./artifacts/target/x86_64-unknown-linux-musl/release/what-bump
            #VERSION=$(what-bump --version)
            VERSION=0.1.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires: [build]
      - publish-github-release:
          requires: [approve-release]