version: 2

jobs:
  build:
    docker:
      - image: ekidd/rust-musl-builder:1.38.0
    steps:
      - checkout
      - run:
          name: Skip "chore" commits
          command: |
            shopt -s nocasematch
            case $(git log --oneline --format=%B -n 1 HEAD) in chore*) exit 1;; esac
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - &cacheKey v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build what-bump
          command: cargo build --release
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: *cacheKey
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/what-bump
